Use vector.assign instead of vector.swap(vector<>())
Try to fix:

/sdna_plus/sDNA/sdna_vs2008/tables.h:91:23: error: non-const lvalue reference to type 'vector<vector<float>>' cannot bind to a temporary of type 'vector<vector<float>> *'
   91 |                 index2_to_data.swap(new vector<vector<float>>(size,vector<float>(size,default_table_value)));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/PROGRA~2/Zig/ZIG-WI~1.0/lib/libcxx/include/vector:716:72: note: passing argument to parameter here
  716 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void swap(vector&)